### ISSUE TITLE
Crash when looking at red crystal recipe in book

### ISSUE THREAD

**Issue by Slikrick** [williewillus/Aura-Cascade#5]
http://pastebin.com/Yn85fvh9

SMP - Alpha 2.1a - Forge 1695 for Minecraft 1.8.9

**Comment by Serolar** [comment]
http://pastebin.com/gHPEn4jA

Aura Cascade v. 0.2.2a forge-11.15.1.1738 for Minecraft v. 1.8.9

This is still happening, it seems. "Better to know, than not know." I hope you have a nice day.
